# This is a basic workflow to help you get started with Actions

name: 'Test Json Parameters'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.ref_name }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: view the environment context
        shell: bash
        run: echo "$ENVIRONMENT_CONTEXT"
        env:
          ENVIRONMENT_CONTEXT: ${{ github.ref_name }}

      - name: view the variables context
        shell: bash
        run: echo "$VARIABLES_CONTEXT"
        env:
          VARIABLES_CONTEXT: ${{ toJson(vars) }}

       
      - name: Merge JSON with template
        # You may pin to the exact commit or the version.
        # uses: mpmxyz/merge-json-with-template@79884260de99e04a77e8db68d72c8544ee03156c
        uses: mpmxyz/merge-json-with-template@v1.0.0
        with:
          # JSON Template that will be merged into the target file ($VAR/$(VAR) will be replaced without any substitution, $$ will become $)
          source-file: ${{ toJson(vars) }}
          # JSON file to be merged
          target-file: 'parameters_json.json'
          # Path within the source file that will be copied from
          #source-path: # optional, default is 
          # Path within the target file that will be pasted into (sibling paths remain unchanged)
          #target-path: # optional, default is 
          # Paths relative to the source path that will not be copied from (separated by newline and trimmed from surrounding whitespace, * to match all paths)
          #skipped-source-paths: # optional, default is 
          # Paths relative to the target path that will be removed unless overridden by the source file (separated by newline and trimmed from surrounding whitespace, * to match all paths)
          #skipped-target-paths: # optional, default is 
          # Paths relative to the source and target that will merge by appending instead of overwriting (separated by newline and trimmed from surrounding whitespace, * to match all paths)
          #appended-array-paths: # optional, default is 
          # A JSON file with values that will substitute $KEYS within the template, overrides the default replacement with environment variables
          #substitution-file: # optional, default is     

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
