name: test2

on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on:  ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:

    # Deploy Custom Vision Model and publish
    - name: Test Vars
      uses: Azure/cli@v2
      with:
        inlineScript: |
          echo Prueba concatenada
          echo ${{ vars.FUNCTION_VARIABLES.VISION_PREDICTION_ENDPOINT }}
          echo Prueba completa
          echo ${{ vars.FUNCTION_VARIABLES}}
          
