name: test

on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on:  ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:

    # Deploy Custom Vision Model and publish
    - name: Test Vars
      uses: azure/powershell@v2
      with:
        inlineScript: |
          Write-Host Prueba completa
          $params = @{
            "modelId"="test"
            "description"="Taggeo de VIN y Placa para todos los 102 documentos"
          } | ConvertTo-Json
          Write-Host $params.description
          Write-Host Prueba Finalizada
        azPSVersion: "latest"
          
          